namespace ivanovGymBackendNetCore.Domain.Entities;

public class Exercise
{
    public int? Id { get; set; }
    public string Name { get; set; } = "";
    public string? Url { get; set; }
    public string? Comment { get; set; }
    public int? MuscleGroup { get; set; }
}

/* create table public.exercises (
  id bigint generated by default as identity not null,
  name text not null default ''::text,
  url text null,
  comment text null,
  muscle_group smallint null,
  constraint exercises_pkey primary key (id)
) TABLESPACE pg_default; */
